Remove legacy converter and unused dependencies (#102)
* Fix demos by replacing old SCIFIO API calls with the newer ones

* Remove unused `net.imagej:imagej-legacy` dependency. Removing this package caused the following error to disappear:
    java.lang.IllegalArgumentException: Invalid service: net.imagej.legacy.LegacyService

* Remove StringToDatasetConverter: it is not needed anymore because
io.scif.convert:StringToDatasetConverter is available.

* Remove uberjar profile and json package version: they have been included in the parent POM.

* Automatically copy plugin into Fiji when possible.
A new build profile copies the plugin JAR into the Fiji's
plugins directory on the install phase.
It is automatically activated when `fiji.home` is defined.


Co-authored-by: Dominik Kutra <k-dominik@users.noreply.github.com>
Co-authored-by: Curtis Rueden <ctrueden@wisc.edu>