Remove net.imagej:imagej-legacy
Removing this package caused the following error to disappear:

    java.lang.IllegalArgumentException: Invalid service: net.imagej.legacy.LegacyService